name: CI

on:
  workflow_dispatch:

jobs:
  build_docker_image_and_push:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      id: docker_build
      uses: docker/build-push-action@v2.2.2
      with:
        push: true
        tags: mambaorg/micromamba:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}