name: CI

on:
  workflow_dispatch:

jobs:
  build_docker_image_and_push:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Check available versions
      id: check_version
      run: |
        python -m pip install requests
        LATEST_VERSION=$(python check_version.py)

        echo "Found Micromamba version that is not released on docker: ${LATEST_VERSION}"
        echo "::set-output name=latest_version::${LATEST_VERSION}"

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: ${{ steps.check_version.outputs.latest_version != "false" }}
    - name: Build and push Docker images
      id: docker_build
      uses: docker/build-push-action@v2.2.2
      with:
        push: true
        tags: |
          mambaorg/micromamba:${{ steps.check_version.outputs.latest_version }}
          mambaorg/micromamba:latest
      if: ${{ steps.check_version.outputs.latest_version != "false" }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      if: ${{ steps.check_version.outputs.latest_version != "false" }}
